reviews:
  path_filters:
    - "!**/*.webp"
    - "!**/*.avif"
    - "!**/*.woff2"
    - "!**/*.jpeg"
    - "!**/*.jpg"
    - "!**/*.png"
    - "!**/*.md"
    - "!public/images/**"
    - "!src/assets/**"
